### ISSUE TITLE
Server crashes when mobs attack Lightning

### ISSUE THREAD

**Issue by dapwestwood** [RevivalPMMP/PureEntitiesX#354] opened 2019-07-24 12:22 UTC
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

## Required Information
  __PocketMine-MP Version:__ (3.9.2)
  __Plugin Version:__ (0.6.2)
  Where you got the plugin: (https://poggit.pmmp.io/r/60547/PureEntitiesX_dev-294.phar)

## Optional Information
  __PHP version:__ 
  __Other Installed Plugins:__ 
  __OS Version:__
    
    

## Steps to reproduce the issue.
1.  It's random causes, i dunno why what is happen, and it was crashing my server
2.  
...

## Description
I think it was caused by entity living armor, and i set all the armor to easy at 100 and it was not fixed, Them i set all armor to 0 and not fixed too.  

```

PocketMine-MP Crash Dump Wed Jul 24 04:46:20 UTC 2019

Error: Call to a member function getContents() on null
File: src/pocketmine/entity/Living
Line: 423
Type: Error

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: PureEntitiesX v0.6.2

Code:
[414] 	/**
[415] 	 * Returns how many armour points this mob has. Armour points provide a percentage reduction to damage.
[416] 	 * For mobs which can wear armour, this should return the sum total of the armour points provided by their
[417] 	 * equipment.
[418] 	 *
[419] 	 * @return int
[420] 	 */
[421] 	public function getArmorPoints() : int{
[422] 		$total = 0;
[423] 		foreach($this->armorInventory->getContents() as $item){
[424] 			$total += $item->getDefensePoints();
[425] 		}
[426] 
[427] 		return $total;
[428] 	}
[429] 
[430] 	/**
[431] 	 * Returns the highest level of the specified enchantment on any armour piece that the entity is currently wearing.
[432] 	 *
[433] 	 * @param int $enchantmentId

Backtrace:
#0 src/pocketmine/entity/Living(466): pocketmine\entity\Living->getArmorPoints()
#1 src/pocketmine/entity/Living(562): pocketmine\entity\Living->applyDamageModifiers(object pocketmine\event\entity\EntityDamageByEntityEvent)
#2 plugins/PureEntitiesX_dev-294.phar/src/revivalpmmp/pureentities/entity/monster/walking/Spider(57): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
#3 plugins/PureEntitiesX_dev-294.phar/src/revivalpmmp/pureentities/entity/monster/WalkingMonster(72): revivalpmmp\pureentities\entity\monster\walking\Spider->attackEntity(object CortexPE\entity\object\Lightning)
#4 plugins/PureEntitiesX_dev-294.phar/src/revivalpmmp/pureentities/entity/monster/WalkingMonster(198): revivalpmmp\pureentities\entity\monster\WalkingMonster->checkAndAttackEntity(object CortexPE\entity\object\Lightning)
#5 src/pocketmine/level/Level(848): revivalpmmp\pureentities\entity\monster\WalkingMonster->onUpdate(integer 21092)
#6 src/pocketmine/level/Level(786): pocketmine\level\Level->actuallyDoTick(integer 21092)
#7 src/pocketmine/Server(2445): pocketmine\level\Level->doTick(integer 21092)
#8 src/pocketmine/Server(2576): pocketmine\Server->checkTickUpdates(integer 21092, double 1563943580.5603)
#9 src/pocketmine/Server(2345): pocketmine\Server->tick()
#10 src/pocketmine/Server(2205): pocketmine\Server->tickProcessor()
#11 src/pocketmine/Server(1784): pocketmine\Server->start()
#12 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
#13 (1): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.9.2 [Protocol 361]
Git commit: 7a747d6f9347273467b5ecc1963998c949ff6a7a
uname -a: Linux b1ea58e5-a35e-4abf-abe3-dddebb89ca9f 4.15.0-1043-aws #45-Ubuntu SMP Mon Jun 24 14:07:03 UTC 2019 x86_64
PHP Version: 7.2.20
Zend version: 3.2.0
OS : Linux, linux

Loaded plugins:
KeepInventory 1.0 by KhoaGamingPro for API(s) 3.0.0
CB-Heads 2.4 by Enes5519 for API(s) 3.0.0
EnchantUI 0.5 by UnknownOre for API(s) 3.0.0
ScoreHud 5.1.1 by JackMD for API(s) 3.0.0
PureEntitiesX 0.6.2 by milk0417, RevivalPMMP for API(s) 3.8.4
PurePerms 1.4.2-c2a by 64FF00 & ProjectInfinity for API(s) 3.0.0
ComplexHealth 1.0.0 by DuooIncc for API(s) 3.7.0
TeaSpoon 1.2.0 by CortexPE for API(s) 3.9.0
MultiWorld 1.5.1 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 3.0.0
EssentialsPE 2.1.0 by LegendsOfMCPE Team for API(s) 3.0.0
Slapper 1.5.0 by jojoe77777 for API(s) 3.9.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
RedstoneCircuit 2.0.0 by tedo0627 for API(s) 3.6.0
EconomyShop 2.0.11 by onebone for API(s) 3.0.0
DevTools 1.13.4 by PocketMine Team for API(s) 3.4.0
AutoClearLagg 3.0.0 by Twisted for API(s) 3.0.0
essentialsTP 1.2.2 by  for API(s) 3.0.0
MysteryCrate 9.1.1 by JackMD, DaPigGuy for API(s) 3.9.0
PortalsPE 1.1.1 by luca28pet for API(s) 3.0.0
WorldProtect 2.3.8 by aliuly for API(s) 3.0.0
SizePlayer 1.1.0 by  for API(s) 3.0.0
ChestShop 2.2.0 by MinecrafterJPN for API(s) 3.0.0
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
AdvancedJoin 1.1.0 by tim03we for API(s) 3.0.0
ShadowAntiCheat 3.6.5 by DarkWav for API(s) 3.0.0
EconomyLand 2.1.2 by onebone for API(s) 3.0.0
FaceLogin 1.1.0 by Muqsit for API(s) 3.0.0
StairSeat 1.4.1 by korado531m7 for API(s) 3.9.0
BlazinFly 1.8.7 by iiFlamiinBlaze for API(s) 3.0.0
HotBlock 1.1.3 by survanetwork for API(s) 3.0.0
VeinMiner 0.1.0 by jasonwynn10 for API(s) 3.0.0
UltraCapes 1.7.0 by SuperStulle007 for API(s) 3.0.0
TimeRanks 2.1.1 by luca28pet for API(s) 3.0.0
SellAll 1.3.0 by AndreasHGK for API(s) 3.0.0
EconomyJob 2.0.5 by onebone for API(s) 3.0.0
FactionsPro 1.3.18 by Tethered_ for API(s) 3.0.0
SimpleWarp 4.0.1 by Falkirks for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtPAtz2zaTfwWjdK5OT9Rblq2OO+faTpPWbnSx86VzZScDkZDImCRYgpSsdPrfb3cBkiDtOE7i
zHcz13Zai3jsG/sAAf7VWcks5vnbjchUKJPOfNTt5GEsOvPhdH98OBlPDwbdTsRVfpZlMuvM/+rk
uxS6O/q524mFUnyNLSc8ilguGWexiJciY6si8XKAytYiP5FJLpJc7T1l0JAUUQRzV/DnWRjh5DTg
2bzf7wcyFn0PBvMwEVl/Ib1rkV/Ab+di0cNBfZV5/ZSaY2juA9Aw3/XPw02YrGFEinA1zPtGwqgI
GjvzyWgMLGfcg9+/d54M2H2z9ib7+0/nrO52Xd3vunqA8wPwepzFMlvIkNgFRE+G9wOd7o8+ApSn
abQ75TEI+kL64SoEde3J5Tvh5c15G5hZTz+jv3rejzv9dIZDiKoRS6NiHSaqvygyQb2hUL+99cXG
GR1OamlnYhNueJTGcdpPYagwQ0s2YpmoHJS15dE1kNu/TENfZHvT2ce4ynPuXX8xH+PH5uON5uNC
P+7NUDvWXNe1J9dUmumua+TguloQJaOa7pLdE5nl4mZxVs/XHSiedZAnAIC4m3xl7oaHB5/IXhOA
84MXCO/6OPGPv4DLaXuFRGACUf8c/793MPlSEmXyOvV5LvZgTYo1uKbRcHA4Isz792GeHbSXO/UC
9fgHFOvlBXi93am8CsGSb0OftaFfigx87d5oMpneC9n/EMSDD0Gcztq06h6jIASnhaCaULvMl8Uy
Eqz2+L3p/mBM2A4/hG18i/4SW450a7c3+NDs0eC+2YtMehBVZGbADD8AZjg7mHwAjMp5lpvpo/b0
OqjsjWYfgvD2rYfWkxVeXhrzj1yJE4iF6lxyWNdddofnKvIwAou8gPB1LtdrHAVAwBZ/H+7/wdrh
reocTW53luteczFme0NaBX8WYSb2zLzZ8A/22aGzHoFx82nnj7+7HfE1wvynhWOgQrP+Nkw2MtqI
GIbC/DDxgXMv75T90NbwidDhSV8g9ZPhBHrdvP/dd9A6GU7piX3HXom8yBLFArllMU92jEOwLjLQ
IYZrlgehYrFcsoCrHjtu9KWZ3IA/B8ZTkXlAE8gD9OEXmnsQiU8RqkcY90uMz2SGEBXbBqEXMI8n
bCt4ZhB3NUoVyCLyARpSB02CqSIGkDmPmFxRA7+LGJ8td9gbZoR0ViJFK0lRbpqYA9NOD4floP8y
6AAgdowGpqNPT0N6SsE1hF5Dx430hs1x+l80Y0Qz3PwbTfcRG3xP7WPTDrmm4F6w9w2yDM4T4bxI
MI7LbEeZk2U+XLFvwlzETzXsiYFRQf/PI91P807FSiRKlERptFMz5W96Qn3Qj5lpNsxrcHqGFpMe
f2jGjwe2IY2HbUNC1QQQy4TKGbnwUl8qFR5maj4TiRfwJEd14KqwrS4UnoDRPKcpekkwsAevyDJ4
inZkK5jZEvaRpcfxuNJjyjMeox7YNxauF37n739S239S239S239S239S239S2//XqW23sxYwlUeY
HSYcd7g6DTBAyRKEUO+Edca9w94Im4sw8jvz4Ww27nZChe6pM1/xSAlIRDOZS08C1PH+EHCEmKjO
+Gwy8/dXh+PJbDQbT/Zny6nwvOEhGOHhgXc4OVyt9vmMA+yMX0fhEuYMesNRbwAthSHuPEyKG7Yc
Cj49EFOHj6fCmfDlyuFLMXZ83xfL5cGhxw9XbNIbTnsDZziYjB2+VezJZOq8XhZJXrDLiwUDV8F+
LhI2mrDhZD6YzQdj9vrqhI0Gw0N2c7D/dn+CKXWQIum9UW+EZLwXiU8y0FRB71upSrKggR4ieqjy
dYWy/UWItErqLGE327udWs5DwsCLPJCZwkzll0DynzjocQ3LBVXH0xDbx70BDIVnkXBY1UAf2DAo
wRcpUItToU/JFaSDVkPMqVJoAHXdBjnaqLEGAetHw3h5efXm5avzU2jaiqWCPBOzQWD05EfnueC+
shirmmyeRr1Jk6ezRKjpFHLvR2KnhOe6i4jvRIYk2L8fwsyZzhVfv7C4qdtsdsBtNtl5nVwncpu8
zMRjMVRDxKTIEPFwxVx6UFw8L3yLlarJ5mTaG/aGTV5+htB+cfpYfGho4GwN9vrXQ9ho1rOWq2rV
ubZq9slLWQzFYXQ9wGKw23mlM4vFBTg4m8EDsM/PZPCeZMWmsub28ur41dXrRYPXIM9TBZ4dHGZQ
LHuejPsWqc18sJTLQmSxaslEtzW9yaQ3crwRb8pkf/Ls2WDA/oPB6sfI9iJZhQlkVo+l9rcagZYB
UWX9/Jjm75AGzbWyYw0HPZCM00jcwBqP8sB2Q432ln9te9jTQsoXiec1uJ99PvclPNdtkNF6fOha
vhL8MpVIe8Vd1dRkbNRmrEzKG4wdfj5jdZLfJP4+my7n9G5275GdiyLKwzcyi2znZDU2WZq23dPJ
e+EFi4tTsUE7+ld4E16f/A+9PNsVuSquQ/h9zaMwvFaPZcweokxjSHTAimOkdIuUghBsqj/VpC1G
+hYgDERKoROBlAo0Z8Uiu7kZXW/lDOeQ9QMbL1cXJ4szBuYSP1qktaiAGoby48/gXhOo6es3OMPo
FfE0FZkdvExL2zhabL+T76SY4T+PZfFKI35Y5L2Dz5qifskDahiSdxnvjheNXKNubIboWTuiyUQs
4b/HUqkBB9W1pgBgQtJhU/NRH/VK+CoHGCdh5hWY9VdctXuahnvLFefCl4P9UVN/+5/PW2bQP8Rj
WZq5DGR6WzXU2mZgOPxy5di6/wRFKaCn0pQh7qOqAodzJWVkpw5VU3N5DcfttL0uEW/7lMkXxEuD
33UtSj4tXaop61cwgNnjIpcnkeDZOV+vLY6b7Tbb49s2ebUNFdjlYy23XINzXUAhPSQiAiJct03T
p7oaQ+ax2kVFfHHSb8LDl1mVm71aWLJoNLcTiqbneSQJ2BjBmJv4P2rAFzvc6tudZDwXdgphN9ts
HH6wxoHFwBfh+qdi91jhoix3bGI+O3ZoYP0GY5j8Q0LVzg3qttYSbnMeFR4fHaQifyxrrjA/vDil
RAcKjxzfXtY8NJqbXhYqtCYbkOAV0aNVKxqa61Jal2oKPiXFtXR2UYTZKhSRb22/OeX+Xg7VYT/m
enPe5hZznvC90PsVdtpTN7b1OvgaC5PwnSM+qNOr3w/aCcI3fq2oWbc1tXmrTEG37WV8BXL5efHr
14icFSlQg1lUfeqKTOUanhyZpQFP+Fr0a2Aggx9xZ1Rk7ejaaL5VsDlLkfPRQ2qcr1HNLDVtuY6+
LUq/pKJpgMJA7G944gn/ZxnahWyj+X4Tx4OYg/H20bJeAw7CsKHhHdAAUbhJ0cd32gLuy+0xBDCw
BW77s3ZPM8vYb+8hnvLs+g3fPBZ7Bhys4+MT+t+Dc99znvi3c19qbVedo39b6hsBOVXqa2j7qK6e
cU+cy3XDAuu2j5jfRfEngHos9Whormuj/7it5TzMLltWVrW1t/1akf9aZmCP0/EwfrTi2AIJJlYS
Yv18CFM/Rvx9mDyL7LcjdVuTqYPerMlUGD6LeByGCc54NNfQhAp+sSTH+vkQ1p7L/McI0gCLs6qp
bW3jJmOqyMAPiRxSkuuvsZ4IvusGMl8iOa5rEfapft+mtV/BAf7/JcIEY7ud0tRtzW37W+vtHVcy
2e6SZDh4LL1aIF23IuThievrKM/4CU+FHd6txqZOZ22OLotUZJd5EUViMJg9FlNNqK5b0/Nwxq7C
WLziybXNV93W9vqfVVKYN8SWodb7+PdwV1HhujZBn2qiFY39Ggo6VBFFx5H9Erxsaapy3FblceJn
gqvnP/3yNRZnDR1PKRBB1Y8HvcnUWH6Wy9txHBvbW1jTf1sYfyeXVRTXlD0kiOPRS4UvwxthvGpt
627YKh6vRB6ITPhvv2wJkgGfBBTlMMu7THls3tAbbi2iKNLjw4Pf4Ib4qugNz9JGPVg12kxOcBuy
yeMzPBeVfek7EACj8quMJ2pFDvsyklvrsbFvX7O9MrhdVxG9W6AX60mL9ge9+SXZNl9wGnG3Ep3h
XS83P81873FGLdv6TWxCWQDHTtne+cB7TyS2/vUIbz0JzN94wARPuAool4m+3h0ngAC04yTS2Ybv
eebTkx8q5N4B9YXEJZ1/6qWZhABC76jnnSeL6omdyGQVrhkeV3eTJ5c8Zz8XERsN2GAwH03mg2l1
bMZNYpn7R24xGPBZpP94Z7+dsRMs6t1EY3JSmeVHw8PhBCZsA+DaiUKVH8nVyk14ksgC6i4npe0O
h3tBKPRZd3UkE4CR8m3imM0ZkPrRcB/Q8hszQR1NBwAlAgN1VhGeOLRm8SSMwUitFjyBTo9rkGMs
fXEEs1cyAwKqFqILROnjgQX9lG5SmuWHq1XoFVG+OxoCDDpKlcvMUSLPw2StjtyEDvk5aLpH+m2h
aVFC+FU33iqAB22Wzp+FyHZHaJpVUwauUaPGX72UKwXQ/KPv6B9guMilo/hGEFmbUGxRzTlWsEcH
bnKzlDcOrgzNulZDmB4NevSvmxDKnq0YKKzWBV+LI0HXEOpdrN4ujtBCGHow5pFxFMA2HoNHG2Eg
PtYwRLAadhUIJVgpF8YzQUe7IQYofdDbQ83nbClYmHhRgWf4Afwt20RYlzIW5jh5G6biK9FlEv26
ojsFSwig12yHp8o1LBauWKxPVCMG0ClenoCUHgD/KrYVuL4vVhw0q9hWJt/mDN/Z4fUEEHQMzHp4
CBQppHsKxPc2EAkr0jXUQngy3SVJa2BzN2HsyZuAAg5eiQB/6TO8MaJP9YEM0JtGPAeiqJtIhfyZ
A2CQZyT0UXgfnI4nWACFbkQSjBGyNthSY3NGORZ2qKDIfYl2ru+pzJnbaaxOxvTpR3YhI0BzWkQF
jEBij3EJMVyYQF95IpltQs7+G20Fx5DRlJuac6YNFqZe4i0SjqahJFBpcGv5cAOKFQo0D44XpE9c
Q8IAI8F3+wqB1D0OkLeUSlgIzmhRlJBAFgyXJl7+AEUgucsdM+rD8WYNVd2WgJ68CUEJMgFdch8v
miitciQVD6YCSRzKGvI/eAFhKVAqICnxZ8Hpvs863MDYDY8KwfYMUnCGTxG6xgirV+DKckDVeD50
Dt2E+9eCLgqBJR+rXeJdcXXNsHYC2+3RgNcKBIPLqeQUhwUZZEkFWAwMV11GToUZ1wNrsAuyiEF2
CgMjyQZCC7bFRQJWi0M08EsyKeAJLDuTN+AZcwFiAJZotSQVcShbQ9CLFa4PuuYE66DLwvxbvPWU
0TRfoEsmM21NZnvAAyicjUgsxIZjOJ0TqPb6IAfOsiLB8+Jo9SB3urjDaKdS9dip2JjfLEY3z7yM
q6BrL3hjmSiRLCvSXLdqgaFgYqDN8EXKBYMDMcHK1IuQb2ToA9l3U4A2gjYnQdBgXT3L0PCgvh5U
WRqEKAgm2U47gp8iuQTrwfSC6XZYaHGYoz+JxZovdzlInF1qUQ9IuDpo0/Qr1No2JMmTRTGMdhpQ
aWSKOFyFQCJ4QbpdgWBWmRAlSm3koK2CludagqIk+gK0CkS0JjIdIm3OBsgFYCe3nwcgZv//PAeY
jd1HP0b1L6Nf5TLV95q0H61IMuAUA/eB4Vr4FUGItaRqOBhNDGHkBN7QqjD0qW8fgUJaF0QSegzr
CpW4EV5B3l1qkvWKxABZjRY3HuQpquZIO66XV2dzdvX8xSU7f3Hx4gqc9+L8xdklW5y9YpDR/nL2
qstgELt6CaPO2JvnL8/P2OLVy5Ozy8te2wU05DGa7htxQBYeSkoC0BErZJCuNZTSqJztEGQPscYn
30JDHHxFqt0sgcL7c2ECDhqsCfn9kLFpI4OUFINugsMMMoKsgYDrrR25jkiE4yXGEMwtaELv9mi0
BVN3gNrMLTgtWSRX61XPrXgA8xKpqlkdDwyv6undJBnOx4bzNc+WsDIcT0aRTpfJAd0tXVpqSI6Z
xcwsvKjJE7r10qAEksECbPBpt4wJbSMszVCH19UKYGl+43oJ9thL7fO1wZc3PktaQggi24TV9CsN
OCXygdH9wcDwCtiekbO4FSTJdDSEirdVJuMy2OrZZoRjm6atYeTGaPKWbbA7TKphHZdlkooqywAT
mqExZL+IU53R6bSRmQ4HO0p9neIgM4FoJzJLDvBa6FbAYud3CBiCNgQ+wLABI1OqEOgY8gC0ti4z
XHRaiK2mqlsq0lzE1fT3NDU49INywlrMC4rkWpW0n/AUW8O4iCHGQnjNWFmcoCKZrtw0FbVccb0Y
UdKKuW1jkOCnhiJC6GDmXUDQnVQaO5W6q23TmBuh19Pw9eByCWlYZqDNGWUOjgclqah4OwVSKFeB
9BGlB9TpBENDSTnWQUzP0RzW3ME0I09TkRvMOLjOdlGAeHqnhHs/qPvs0E3M5vzchAhIzQIZ6RRz
yXMotTHVJ5IhawITMkGGfJuutkyvDi1LUSWbOrw9sbVUdqFbzXY5Au8yZ2gpkJRHiJ28JMaEAPLa
dR6rrxAXmA8T51g/UaKPk6HRkNVjz/HOccaOKLljJ4vXXZgLNCxhfW1DH8yecgXtPSv4DsGfs1mZ
dtcZuSLpWGN77NgHRxXwaNWH8lWXCb4AGzaoACnDHR40MGsh1mHPAmaXImc36NUwxeRRVztNRP0m
TKCEA9bA+wjyZZhJv14kizIPr+tRLDNw0hYiKsIs0iR1zHOr8LkwC1KF70WlaszYSw0rupetsynI
6LXlWFF3cjjSk5722MLMiXi2pgncFMbGTAjjKuNr5A7UBWypNKJkBqvdGIhHP8AzVOFJFOJuD5Xv
ePkNr5BfXL0mShWwhGwvi5zhdgFpuUan645e6YbivHBw1pyoxQXgi2Wxnpe1zA9siDWMyeSwaqX+
smJVur4XZSWL04yhDBGY9lsa2kkgoUZF4yxLGFEWqeTcfJ5zpvimdKK4V1PucWFfvd45xHTwBILn
pY8BSvVbkzJlpnILTIjSFZVChkbpSyK9KEwZzQU5XvAdyBCNJZabsoJF9298pt4kK/s0SlV7i3Kb
yt7BuKItCG0A+hNZevOGxhptF8qU+h5Yfa79gpnj6DlzlkJCsQkjRKN9nlnPBgs6bZ6sq6Q6wWlR
O3Z0y1GN7a47d410lXccywJteqWdszFxFKXeOqRghMuZandQDP6maAKTX1FssSYT44nQteJSaGBL
gV9zYLS5SOEgKC2AlE57jo0opdlHRBX7sDIZb5Oa6huy+NkECAB3UTm4m0yeASSf9l3IEIHYcjL+
ragZk3VjJe0U+tKw5S3odCohoq1aayvmxSkho5fHipYkylNkqGnIa8F1xcxwx8zOQxntaE6DdYDn
sBF7wtZQs6haPPXuRiWh3m0RmcW65SEVNeA4IOPXukllWkSlMZoHdPs0xriIA8RHybCTmlWNzhUX
6pyVaSbts+rtnLkJeLj7RCWWbtbxwqgLvwlQ7Qv4tdjQ3B38KEurqVptzeY0gMxsJS2FwCJz9IuC
amQgUTFESg9vofVCSRQnMtnFWCLA+shxO89TNelY95h+VvcTC+Sx+HqdQbGpN5aqnTtMpPADGtdt
/og+WMAvT1/ixWXH+EAdCtAnbIXOQzmsnC1hVER4zQC19aztZog8leS1ZWrl3BIq6FP3G1uCoJc4
xnXb6RS1S1t0kKEmaCbWLk8X3GMa8C7DY3kUr/IqYwHPuxJQRYMKwQElGA90bxlX9J4Rb+wamVdV
VrwpIDuD0EZOrPQVBiBpXveXOG5pWvNqqzoP49pVm4BE32GB8WXegJpFf4kIaTvMTCq3Pns1AtNj
YyileX/IM15ba1evCmuXodwWzsPcyLPcTwhMIzkMLAhMjmkcBm7PQhrvU5IVripAkKkDI3r/Hx1Q
WWRrFwfwjIcsAxuPQq5MBg9JF8fXkeYJcwCg0ehqXipN94Hd4m7PnP1OwRvCZ5e2f/5AoJSc11HS
fi9BbGAileFnkqjALl8UUeV8V8CieE4BWlEuSYUZXg4DWk20tcnXeIkG/ZPh6yUMCjp41Rjn7Nn5
8dV89P2sOz28GXbHN+Pu6Pvh977wpHaxe3g62UPfenQw0J5YP02mT3XWo/f77bpWr3AMLSBjs+1E
mQftG4HWvB3TX1YostInl8l8Vm3kk8cBOBCpPHo5o0qBOeVbBrAFnd49eUauhlDR+AaQghIF87ks
q8WhXKtX75DJlEpBcQOOT5k6yLvGdFlRzg8SWYYRfn2ISmYah/wCKZCl6yii14zmkuBDLpIZX9jp
dsRNLhJF74fnf+HNSWF/UMCnywv1MxhAolRkN6Vec4r6EwgS48ZnCfTXEqrnpQdpVmC34IukxOdZ
oy3bpbmkU1djOjfgma+b1SOKrEHKO2Vetu/TQZhVGOWiAXKVNz6XsPYbT3GjM4BIVX3nAJM3H99Q
WwMuF+f2I5m9r78KMSJ646V+fWaPincgH/pIg/nFpngqYoS78szB19TTwWQwg5/fvMANpOnh0Ofc
H418MTiYjiajw6kYLv3BbAxGJVar4VDsT2eH7BvSRJI35LEISKJ4dmbUeEn6lnIS+jSIdaotlSq8
aajWbHuZT0oM8Rsa3U4mQO5oMetCS6Sc/0qszOZFwx6CWDYEq4gM1TAzZc6ZH8JDuF6GCcfPUNCJ
CJRkLq9FAmlQQ5k7Tm96kTu8//U+TPUZxSk9knjDevzff/8vKhmPag==
===END CRASH DUMP===

```

**Comment by 95CivicSi** [comment] 2019-08-11 17:42
This is happening because a monster is trying to attack Lightning.  A temporary fix for this is to disable Lightning in TeaSpoon.  The resolution for this will be somewhat involved.

**Comment by 95CivicSi** [comment] 2019-08-11 17:46
Duplicate of #321

**Closed by 95CivicSi** 2019-08-11 17:46 UTC
Labels: Category: Bug, Resolution: Duplicate
