### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by mote166** [RevivalPMMP/PureEntitiesX#386] opened 2020-05-16 15:39 UTC
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

## Required Information
  __PocketMine-MP Version:__ 3.12.0
  __Plugin Version:__ 0.6.4
  Where you got the plugin: github downloaded about 2 hours ago

## Optional Information

  __PHP version:__  7.3.13
  __Other Installed Plugins:__ 3.3.13
  __OS Version:__ Linux, linux
    
    

## Steps to reproduce the issue.
1.  
2.  
...

## Description
  
idk how it happens

```
Error: Start and end points are the same, giving a zero direction vector
File: vendor/pocketmine/math/src/VoxelRayTrace
Line: 62
Type: InvalidArgumentException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: PureEntitiesX v0.6.4

Code:
[53] 	 * @param Vector3 $end
[54] 	 *
[55] 	 * @return \Generator|Vector3[]
[56] 	 */
[57] 	public static function betweenPoints(Vector3 $start, Vector3 $end) : \Generator{
[58] 		$currentBlock = $start->floor();
[59] 
[60] 		$directionVector = $end->subtract($start)->normalize();
[61] 		if($directionVector->lengthSquared() <= 0){
[62] 			throw new \InvalidArgumentException("Start and end points are the same, giving a zero direction vector");
[63] 		}
[64] 
[65] 		$radius = $start->distance($end);
[66] 
[67] 		$stepX = $directionVector->x <=> 0;
[68] 		$stepY = $directionVector->y <=> 0;
[69] 		$stepZ = $directionVector->z <=> 0;
[70] 
[71] 		//Initialize the step accumulation variables depending how far into the current block the start position is. If
[72] 		//the start position is on the corner of the block, these will be zero.

Backtrace:
#0 plugins/PureEntitiesX-master/src/revivalpmmp/pureentities/InteractionHelper(78): pocketmine\math\VoxelRayTrace::betweenPoints(object pocketmine\math\Vector3, object pocketmine\math\Vector3)
#1 plugins/PureEntitiesX-master/src/revivalpmmp/pureentities/task/InteractionTask(58): revivalpmmp\pureentities\InteractionHelper::getEntityPlayerLookingAt(object pocketmine\Player, integer 3, boolean 1)
#2 src/pocketmine/scheduler/TaskHandler(134): revivalpmmp\pureentities\task\InteractionTask->onRun(integer 28091)
#3 src/pocketmine/scheduler/TaskScheduler(176): pocketmine\scheduler\TaskHandler->run(integer 28091)
#4 src/pocketmine/plugin/PluginManager(643): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 28091)
#5 src/pocketmine/Server(2380): pocketmine\plugin\PluginManager->tickSchedulers(integer 28091)
#6 src/pocketmine/Server(2143): pocketmine\Server->tick()
#7 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
#8 src/pocketmine/Server(1584): pocketmine\Server->start()
#9 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /home/minecraft/multicraft/servers/server22957/, string[55] /home/minecraft/multicraft/servers/server22957/plugins/)
#10 src/pocketmine/PocketMine(296): pocketmine\server()
#11 (11): require(string[113] phar:///home/minecraft/multicraft/jar/versions/PocketMine/PocketMine-MP-3.12.0.p)

PocketMine-MP version: 3.12.0 [Protocol 390]
Git commit: 77d45bf11674a1360f58e32a14a3b09f423d860c
uname -a: Linux BH21 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64
PHP Version: 7.3.13
Zend version: 3.3.13
OS : Linux, linux

```

**Comment by 95CivicSi** [comment] 2020-05-28 09:47
Appears to be a duplicate of #385

**Closed by 95CivicSi** 2020-05-28 09:47 UTC
