### ISSUE TITLE
Error: "Call to a member function getEntities() on null"

### ISSUE THREAD

**Issue by bluetigeresw** [RevivalPMMP/PureEntitiesX#228] opened 2017-09-27 02:10 UTC
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
```
[01:50:28] [Server thread/CRITICAL]: Error: "Call to a member function getEntities() on null" (EXCEPTION) in "PureEntitiesX_dev-118.phar/src/revivalpmmp/pureentities/entity/BaseEntity" at line 436
[01:50:28] [Server thread/DEBUG]: #0 PureEntitiesX_dev-118.phar/src/revivalpmmp/pureentities/entity/BaseEntity(419): revivalpmmp\pureentities\entity\BaseEntity->getTamedMobs(pocketmine\Player object)
[01:50:28] [Server thread/DEBUG]: #1 PureEntitiesX_dev-118.phar/src/revivalpmmp/pureentities/entity/monster/walking/Skeleton(99): revivalpmmp\pureentities\entity\BaseEntity->checkTamedMobsAttack(pocketmine\Player object)
[01:50:28] [Server thread/DEBUG]: #2 PureEntitiesX_dev-118.phar/src/revivalpmmp/pureentities/entity/monster/WalkingMonster(67): revivalpmmp\pureentities\entity\monster\walking\Skeleton->attackEntity(pocketmine\Player object)
[01:50:28] [Server thread/DEBUG]: #3 PureEntitiesX_dev-118.phar/src/revivalpmmp/pureentities/entity/monster/WalkingMonster(195): revivalpmmp\pureentities\entity\monster\WalkingMonster->checkAndAttackEntity(pocketmine\Player object)
[01:50:28] [Server thread/DEBUG]: #4 src/pocketmine/level/Level(708): revivalpmmp\pureentities\entity\monster\WalkingMonster->onUpdate(integer 27812)
[01:50:28] [Server thread/DEBUG]: #5 src/pocketmine/Server(2357): pocketmine\level\Level->doTick(integer 27812)
[01:50:28] [Server thread/DEBUG]: #6 src/pocketmine/Server(2512): pocketmine\Server->checkTickUpdates(integer 27812, double 1506477028.1947)
[01:50:28] [Server thread/DEBUG]: #7 src/pocketmine/Server(2253): pocketmine\Server->tick()
[01:50:28] [Server thread/DEBUG]: #8 src/pocketmine/Server(2132): pocketmine\Server->tickProcessor()
[01:50:28] [Server thread/DEBUG]: #9 src/pocketmine/Server(1714): pocketmine\Server->start()
[01:50:28] [Server thread/DEBUG]: #10 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/sergiu/Desktop/PocketMine/PocketMine-MP.phar/, string /home/sergiu/Desktop/PocketMine/, string /home/sergiu/Desktop/PocketMine/plugins/)
[01:50:28] [Server thread/DEBUG]: #11 /home/sergiu/Desktop/PocketMine/PocketMine-MP.phar(1): require(string phar:///home/sergiu/Desktop/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
```

## Reproducing the issue
1. Not entirely sure

## Client information
PocketMine-MP Version: most recent version
Plugin Version: most recent version
PHP version: 7.2

## Optional information
...

**Comment by 95CivicSi** [comment] 2017-09-27 10:49
I cannot duplicate this issue using commit https://github.com/RevivalPMMP/PureEntitiesX/commit/2dc3e229746688c03c71bb521a2cede030e02b87.  It appears that this happened when you (or someone else) started fighting a skeleton. Please update your plugin with the linked version and let us know if that changes anything.

**Comment by jasonwynn10** [comment] 2017-09-27 21:29
`Call to a member function getEntities() on null" (EXCEPTION) in "PureEntitiesX_dev-118.phar/src/revivalpmmp/pureentities/entity/BaseEntity" at line 436` is the issue here. I cannot reproduce however

**Comment by 95CivicSi** [comment] 2017-10-07 10:03
Closing due to inability to duplicate.

**Closed by 95CivicSi** 2017-10-07 10:03 UTC
Labels: Category: Bug, Status: Unconfirmed
