### ISSUE TITLE
Bug task

### ISSUE THREAD

**Issue by NycuRO** [RevivalPMMP/PureEntitiesX#137] opened 2017-02-17 19:20 UTC
```
[Tesseract] [21:04:59] CRITICAL> Could not execute task revivalpmmp\pureentities\task\InteractionTask: Start block missed in BlockIterator
[Tesseract] [21:04:59] CRITICAL> InvalidStateException: "Start block missed in BlockIterator" (EXCEPTION) in "/src/pocketmine/utils/BlockIterator" at line 152
[Tesseract] [21:05:00] CRITICAL> Could not execute task revivalpmmp\pureentities\task\InteractionTask: Start block missed in BlockIterator
[Tesseract] [21:05:00] CRITICAL> InvalidStateException: "Start block missed in BlockIterator" (EXCEPTION) in "/src/pocketmine/utils/BlockIterator" at line 152
```

Version: 1.0.3
Ubuntuu 14.04.5 LTS 64bit

Uses: https://github.com/RevivalPMMP/PureEntitiesX/commit/fc79f0344c16a075dbed87363e96b597882e2ce8

**Comment by kniffo80** [comment] 2017-02-17 19:41
Interesting ... I've also Tesseract running with latest master. I do not have this exception ... Are you using master branch of both?

**Comment by NycuRO** [comment] 2017-02-17 19:56
Master.

**Comment by AppleDevelops** [comment] 2017-02-17 20:39
Also unable to reproduce

**Comment by NycuRO** [comment] 2017-02-17 20:46
@AppleDevelops I don't watch how reproduce, i'm on in server, and show that error on console. Not spam, show 1 times.

**Comment by kniffo80** [comment] 2017-02-18 17:48
Maybe its a timing problem. This may be the reason for this only coming up once.

**Comment by kniffo80** [comment] 2017-02-21 12:50
I'll close this issue as no one (including NycuRO) can reproduce this.

**Closed by kniffo80** 2017-02-21 12:50 UTC

**Comment by NycuRO** [comment] 2017-02-21 13:15
@kniffo80 Sorry, i'm used: kniffo80 branch.

**Comment by kniffo80** [comment] 2017-02-21 13:44
I use that too with Tesseract (latest master) and I'm not getting this error. So is this still valid?
