### ISSUE TITLE
Working Horses

### ISSUE THREAD

**Issue by CupidonSauce173** [RevivalPMMP/PureEntitiesX#333] opened 2018-09-25 23:30 UTC
It's more a features request...
Can you make the horses so we can ride them ?

**Comment by Katana-Steel** [comment] 2019-03-25 20:22
duplicate of #246

**Comment by CupidonSauce173** [comment] 2019-04-03 20:20
So it won't happen?

**Comment by jasonwynn10** [comment] 2019-04-04 03:20
Unfortunately, the development time it takes for a new feature to be added is extremely long. I wouldn't get your hopes up.

Closing as duplicate #246

**Closed by jasonwynn10** 2019-04-04 03:20 UTC
