### ISSUE TITLE
Error : Could not execute task revivalpmmp\pureentities\task\AutoSpawnTask

### ISSUE THREAD

**Issue by teracube** [RevivalPMMP/PureEntitiesX#222] opened 2017-09-23 14:35 UTC
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

```
Error : Could not execute task revivalpmmp\pureentities\task\AutoSpawnTask
conflict PureEntities and PiggycustomEnchants ?


2017-09-23 [13:10:51] [Server thread/CRITICAL]: Could not execute task revivalpmmp\pureentities\task\AutoSpawnTask: Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3Obj() must be an instance of pocketmine\math\Vector3, null given, called in phar:///home/gsp_1376/g7.hmserv.eu-19132/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/AddEntityPacket.php on line 95
2017-09-23 [13:10:51] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3Obj() must be an instance of pocketmine\math\Vector3, null given, called in phar:///home/gsp_1376/g7.hmserv.eu-19132/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/AddEntityPacket.php on line 95" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 438
2017-09-23 [13:10:51] [Server thread/DEBUG]: #0 src/pocketmine/network/mcpe/protocol/AddEntityPacket(95): pocketmine\network\mcpe\protocol\DataPacket->putVector3Obj(NULL )
2017-09-23 [13:10:51] [Server thread/DEBUG]: #1 src/pocketmine/network/mcpe/protocol/DataPacket(90): pocketmine\network\mcpe\protocol\AddEntityPacket->encodePayload()
2017-09-23 [13:10:51] [Server thread/DEBUG]: #2 src/pocketmine/network/mcpe/RakLibInterface(208): pocketmine\network\mcpe\protocol\DataPacket->encode()
2017-09-23 [13:10:51] [Server thread/DEBUG]: #3 src/pocketmine/Player(1116): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\AddEntityPacket object, boolean , boolean )
2017-09-23 [13:10:51] [Server thread/DEBUG]: #4 src/pocketmine/Player(1078): pocketmine\Player->sendDataPacket(pocketmine\network\mcpe\protocol\AddEntityPacket object, boolean , boolean )
2017-09-23 [13:10:51] [Server thread/DEBUG]: #5 PiggyCustomEnchants_dev-77.phar/src/PiggyCustomEnchants/Entities/PigProjectile(122): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\AddEntityPacket object)
2017-09-23 [13:10:51] [Server thread/DEBUG]: #6 src/pocketmine/entity/Entity(1903): PiggyCustomEnchants\Entities\PigProjectile->spawnTo(pocketmine\Player object)
2017-09-23 [13:10:51] [Server thread/DEBUG]: #7 PureEntitiesX_dev-31.phar/src/revivalpmmp/pureentities/PureEntities(299): pocketmine\entity\Entity->spawnToAll()
2017-09-23 [13:10:51] [Server thread/DEBUG]: #8 PureEntitiesX_dev-31.phar/src/revivalpmmp/pureentities/task/spawners/BaseSpawner(204): revivalpmmp\pureentities\PureEntities->scheduleCreatureSpawn(pocketmine\level\Position object, integer 12, pocketmine\level\Level object, string Animal, boolean )
2017-09-23 [13:10:51] [Server thread/DEBUG]: #9 PureEntitiesX_dev-31.phar/src/revivalpmmp/pureentities/task/spawners/animal/PigSpawner(57): revivalpmmp\pureentities\task\spawners\BaseSpawner->spawnEntityToLevel(pocketmine\level\Position object, integer 12, pocketmine\level\Level object, string Animal)
2017-09-23 [13:10:51] [Server thread/DEBUG]: #10 PureEntitiesX_dev-31.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(82): revivalpmmp\pureentities\task\spawners\animal\PigSpawner->spawn(pocketmine\level\Position object, pocketmine\Player object)
2017-09-23 [13:10:51] [Server thread/DEBUG]: #11 src/pocketmine/scheduler/TaskHandler(160): revivalpmmp\pureentities\task\AutoSpawnTask->onRun(integer 5101)
2017-09-23 [13:10:51] [Server thread/DEBUG]: #12 src/pocketmine/scheduler/ServerScheduler(326): pocketmine\scheduler\TaskHandler->run(integer 5101)
2017-09-23 [13:10:51] [Server thread/DEBUG]: #13 src/pocketmine/Server(2494): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 5101)
2017-09-23 [13:10:51] [Server thread/DEBUG]: #14 src/pocketmine/Server(2238): pocketmine\Server->tick()
2017-09-23 [13:10:51] [Server thread/DEBUG]: #15 src/pocketmine/Server(2117): pocketmine\Server->tickProcessor()
2017-09-23 [13:10:51] [Server thread/DEBUG]: #16 src/pocketmine/Server(1699): pocketmine\Server->start()
2017-09-23 [13:10:51] [Server thread/DEBUG]: #17 src/pocketmine/PocketMine(553): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/gsp_1376/g7.hmserv.eu-19132/PocketMine-MP.phar/, string /home/gsp_1376/g7.hmserv.eu-19132/, string /home/gsp_1376/g7.hmserv.eu-19132/plugins/)
2017-09-23 [13:10:51] [Server thread/DEBUG]: #18 /home/gsp_1376/g7.hmserv.eu-19132/PocketMine-MP.phar(1): require(string phar:///home/gsp_1376/g7.hmserv.eu-19132/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

Reproducing the issue
Install
PocketMine-MP 1.7dev-66 v1.2 ALPHA8
PureEntitiesX 0.2.5-3.mcpe1.2
https://poggit.pmmp.io/r/12124/PureEntitiesX_dev-31.phar

Client information

PocketMine-MP version: 1.7dev #66 [Protocol 137; API 3.0.0-ALPHA8]
PureEntitiesX 0.2.5-3.mcpe1.2
https://poggit.pmmp.io/r/12124/PureEntitiesX_dev-31.phar
PHP Version: 7.2.0RC1
Zend version: 3.2.0-dev
OS : Linux, linux

Plugins
AlwaysSpawn 2.2.3-1.alpha8; ChatToDiscord 1.1.0; VPNGuard 1.0.6; ItemCasePE 1.2.0-alpha8; AllSigns 1.0.3; EconomyAPI 5.7.1-1.alpha8; PiggyCustomEnchants 1.0.2; KillMoney 1.1.3; SimpleAuth 2.1.0-map.5; essentialsTP 1.2.0-1.alpha8; iProtector 4.0.3#3.1b; Parkour 1.5.6-1.alpha8; PurePerms 1.4.1-1.alpha8; Slapper 1.3.6; BanItem 2.3.2-1.alpha8; PureEntitiesX 0.2.5-3.mcpe1.2; xyz 1.0.3; SimpleAuthHelper 2.0.6-1.alpha8; EconomyShop 2.0.8-1.alpha8; PureChat 1.4.10-2.alpha8; FactionsPro 1.3.11-2.alpha8
```

Thanks

**Updated to put error in code block.

**Comment by 95CivicSi** [comment] 2017-09-23 14:53
This conflict appears to be caused by PiggyCustomEnchants being installed with PureEntitiesX.  We may not be able to resolve this.

**Comment by jasonwynn10** [comment] 2017-09-23 15:59
Why was a PigProjectile set to be in a spawner...?

**Comment by teracube** [comment] 2017-09-24 03:49
@jasonwynn10 
sorry i don't know what's happened
thanks

**Comment by 95CivicSi** [comment] 2017-09-25 10:22
Teracube, can you please test this version and see if it solves your problem.
[PureEntitiesX_v0.2.6-PM1.7dev65.zip](https://github.com/RevivalPMMP/PureEntitiesX/files/1329084/PureEntitiesX_v0.2.6-PM1.7dev65.zip)

**Comment by teracube** [comment] 2017-09-25 11:19
@95CivicSi 
thanks, i tried dev65.zip but problem not solved


2017-09-25 [13:10:35] [Server thread/CRITICAL]: Could not execute task revivalpmmp\pureentities\task\AutoSpawnTask: Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3Obj() must be an instance of pocketmine\math\Vector3, null given, called in phar:///home/gsp_xxxx/gx.hmserv.eu-xxxxx/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/AddEntityPacket.php on line 95
2017-09-25 [13:10:35] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3Obj() must be an instance of pocketmine\math\Vector3, null given, called in phar:///home/gsp_xxxx/gx.hmserv.eu-xxxxx/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/AddEntityPacket.php on line 95" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 438
2017-09-25 [13:10:35] [Server thread/DEBUG]: #0 src/pocketmine/network/mcpe/protocol/AddEntityPacket(95): pocketmine\network\mcpe\protocol\DataPacket->putVector3Obj(NULL )
2017-09-25 [13:10:35] [Server thread/DEBUG]: #1 src/pocketmine/network/mcpe/protocol/DataPacket(90): pocketmine\network\mcpe\protocol\AddEntityPacket->encodePayload()
2017-09-25 [13:10:35] [Server thread/DEBUG]: #2 src/pocketmine/network/mcpe/RakLibInterface(208): pocketmine\network\mcpe\protocol\DataPacket->encode()
2017-09-25 [13:10:35] [Server thread/DEBUG]: #3 src/pocketmine/Player(1116): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\AddEntityPacket object, boolean , boolean )
2017-09-25 [13:10:35] [Server thread/DEBUG]: #4 src/pocketmine/Player(1078): pocketmine\Player->sendDataPacket(pocketmine\network\mcpe\protocol\AddEntityPacket object, boolean , boolean )
2017-09-25 [13:10:35] [Server thread/DEBUG]: #5 PiggyCustomEnchants_dev-77.phar/src/PiggyCustomEnchants/Entities/PigProjectile(122): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\AddEntityPacket object)
2017-09-25 [13:10:35] [Server thread/DEBUG]: #6 src/pocketmine/entity/Entity(1903): PiggyCustomEnchants\Entities\PigProjectile->spawnTo(pocketmine\Player object)
2017-09-25 [13:10:35] [Server thread/DEBUG]: #7 PureEntitiesX_v0.2.6-PM1.7dev65.phar/src/revivalpmmp/pureentities/PureEntities(275): pocketmine\entity\Entity->spawnToAll()
2017-09-25 [13:10:35] [Server thread/DEBUG]: #8 PureEntitiesX_v0.2.6-PM1.7dev65.phar/src/revivalpmmp/pureentities/task/spawners/BaseSpawner(204): revivalpmmp\pureentities\PureEntities->scheduleCreatureSpawn(pocketmine\level\Position object, integer 12, pocketmine\level\Level object, string Animal, boolean )
2017-09-25 [13:10:35] [Server thread/DEBUG]: #9 PureEntitiesX_v0.2.6-PM1.7dev65.phar/src/revivalpmmp/pureentities/task/spawners/animal/PigSpawner(57): revivalpmmp\pureentities\task\spawners\BaseSpawner->spawnEntityToLevel(pocketmine\level\Position object, integer 12, pocketmine\level\Level object, string Animal)
2017-09-25 [13:10:35] [Server thread/DEBUG]: #10 PureEntitiesX_v0.2.6-PM1.7dev65.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(82): revivalpmmp\pureentities\task\spawners\animal\PigSpawner->spawn(pocketmine\level\Position object, pocketmine\Player object)
2017-09-25 [13:10:35] [Server thread/DEBUG]: #11 src/pocketmine/scheduler/TaskHandler(160): revivalpmmp\pureentities\task\AutoSpawnTask->onRun(integer 10501)
2017-09-25 [13:10:35] [Server thread/DEBUG]: #12 src/pocketmine/scheduler/ServerScheduler(326): pocketmine\scheduler\TaskHandler->run(integer 10501)
2017-09-25 [13:10:35] [Server thread/DEBUG]: #13 src/pocketmine/Server(2493): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 10501)
2017-09-25 [13:10:35] [Server thread/DEBUG]: #14 src/pocketmine/Server(2237): pocketmine\Server->tick()
2017-09-25 [13:10:35] [Server thread/DEBUG]: #15 src/pocketmine/Server(2116): pocketmine\Server->tickProcessor()
2017-09-25 [13:10:35] [Server thread/DEBUG]: #16 src/pocketmine/Server(1698): pocketmine\Server->start()
2017-09-25 [13:10:35] [Server thread/DEBUG]: #17 src/pocketmine/PocketMine(553): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/gsp_xxxx/gx.hmserv.eu-xxxxx/PocketMine-MP.phar/, string /home/gsp_xxxx/gx.hmserv.eu-xxxxx/, string /home/gsp_xxxx/gx.hmserv.eu-xxxxx/plugins/)
2017-09-25 [13:10:35] [Server thread/DEBUG]: #18 /home/gsp_xxxx/gx.hmserv.eu-xxxxx/PocketMine-MP.phar(1): require(string phar:///home/gsp_xxxx/gx.hmserv.eu-xxxxx/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

2017-09-25 [13:11:05] [Server thread/INFO]: SheepSpawner: scheduleCreatureSpawn (pos: Position(level=world,x=-136.2964,y=70.8,z=23652.1758))
2017-09-25 [13:11:20] [Server thread/INFO]: RabbitSpawner: scheduleCreatureSpawn (pos: Position(level=world,x=582.8857,y=67.5,z=1129.0869)) as adult
2017-09-25 [13:11:20] [Server thread/INFO]: RabbitSpawner: scheduleCreatureSpawn (pos: Position(level=world,x=582.8857,y=68,z=1129.0869)) as baby
2017-09-25 [13:12:05] [Server thread/INFO]: ChickenSpawner: scheduleCreatureSpawn (pos: Position(level=world,x=604.9299,y=68.7,z=1105.9048))
2017-09-25 [13:12:35] [Server thread/INFO]: ChickenSpawner: scheduleCreatureSpawn (pos: Position(level=world,x=606.8596,y=67.7,z=1118.6788))

**Comment by 95CivicSi** [comment] 2017-09-25 11:27
Just to be sure, you deleted all of the original plugin files for PureEntitiesX, removed the updated PureEntitesX.phar file from the .zip file and uploaded it to your plugins folder?

**Comment by 95CivicSi** [comment] 2017-09-25 11:31
Also, when pasting in text from the console, please use the 'Insert Code' option.

![image](https://user-images.githubusercontent.com/3009473/30806365-829659f8-a1c3-11e7-80f8-eacbfe12b7a5.png)

**Comment by teracube** [comment] 2017-09-25 11:35
@95CivicSi 

yes i deleted of the original plugin files for PureEntitiesX, removed the updated PureEntitesX.phar file from the .zip file and uploaded it to your plugins folder

thanks for past option

**Comment by 95CivicSi** [comment] 2017-09-25 11:42
Can you upload a copy of your server.log file please.

**Comment by teracube** [comment] 2017-09-25 12:41
@95CivicSi 
find log files
[log.zip](https://github.com/RevivalPMMP/PureEntitiesX/files/1329418/log.zip)

**Comment by 95CivicSi** [comment] 2017-09-25 12:51
Ok. I'm going to try and recreate your problem. I should have more info tomorrow morning.

**Comment by teracube** [comment] 2017-09-25 12:52
thanks ;-)

**Comment by 95CivicSi** [comment] 2017-09-26 19:32
This updates should help with most of the remaining problems similar to this.

https://github.com/RevivalPMMP/PureEntitiesX/commit/2dc3e229746688c03c71bb521a2cede030e02b87

**Comment by teracube** [comment] 2017-09-26 21:18
@95CivicSi 
at the moment no problem with 2dc3e22 excepted conflict appears to be caused by PiggyCustomEnchants being installed with PureEntitiesX
`2017-09-26 [23:03:05] [Server thread/CRITICAL]: Could not execute task revivalpmmp\pureentities\task\AutoSpawnTask: Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3Obj() must be an instance of pocketmine\math\Vector3, null given, called in phar:///home/gsp_1476/g3.hmserv.eu-19132/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/AddEntityPacket.php on line 95
2017-09-26 [23:03:05] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3Obj() must be an instance of pocketmine\math\Vector3, null given, called in phar:///home/gsp_1476/g3.hmserv.eu-19132/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/AddEntityPacket.php on line 95" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 446
2017-09-26 [23:03:05] [Server thread/DEBUG]: #0 src/pocketmine/network/mcpe/protocol/AddEntityPacket(95): pocketmine\network\mcpe\protocol\DataPacket->putVector3Obj(NULL )
2017-09-26 [23:03:05] [Server thread/DEBUG]: #1 src/pocketmine/network/mcpe/protocol/DataPacket(98): pocketmine\network\mcpe\protocol\AddEntityPacket->encodePayload()
2017-09-26 [23:03:05] [Server thread/DEBUG]: #2 src/pocketmine/network/mcpe/RakLibInterface(208): pocketmine\network\mcpe\protocol\DataPacket->encode()
2017-09-26 [23:03:05] [Server thread/DEBUG]: #3 src/pocketmine/Player(1128): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\AddEntityPacket object, boolean , boolean )
2017-09-26 [23:03:05] [Server thread/DEBUG]: #4 src/pocketmine/Player(1090): pocketmine\Player->sendDataPacket(pocketmine\network\mcpe\protocol\AddEntityPacket object, boolean , boolean )
2017-09-26 [23:03:05] [Server thread/DEBUG]: #5 PiggyCustomEnchants_dev-77.phar/src/PiggyCustomEnchants/Entities/PigProjectile(122): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\AddEntityPacket object)
2017-09-26 [23:03:05] [Server thread/DEBUG]: #6 src/pocketmine/entity/Entity(1903): PiggyCustomEnchants\Entities\PigProjectile->spawnTo(pocketmine\Player object)
2017-09-26 [23:03:05] [Server thread/DEBUG]: #7 PureEntitiesX_dev-118.phar/src/revivalpmmp/pureentities/PureEntities(277): pocketmine\entity\Entity->spawnToAll()
2017-09-26 [23:03:05] [Server thread/DEBUG]: #8 PureEntitiesX_dev-118.phar/src/revivalpmmp/pureentities/task/spawners/BaseSpawner(204): revivalpmmp\pureentities\PureEntities->scheduleCreatureSpawn(pocketmine\level\Position object, integer 12, pocketmine\level\Level object, string Animal, boolean )
2017-09-26 [23:03:05] [Server thread/DEBUG]: #9 PureEntitiesX_dev-118.phar/src/revivalpmmp/pureentities/task/spawners/animal/PigSpawner(57): revivalpmmp\pureentities\task\spawners\BaseSpawner->spawnEntityToLevel(pocketmine\level\Position object, integer 12, pocketmine\level\Level object, string Animal)
2017-09-26 [23:03:05] [Server thread/DEBUG]: #10 PureEntitiesX_dev-118.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(82): revivalpmmp\pureentities\task\spawners\animal\PigSpawner->spawn(pocketmine\level\Position object, pocketmine\Player object)
2017-09-26 [23:03:05] [Server thread/DEBUG]: #11 src/pocketmine/scheduler/TaskHandler(160): revivalpmmp\pureentities\task\AutoSpawnTask->onRun(integer 20401)
2017-09-26 [23:03:05] [Server thread/DEBUG]: #12 src/pocketmine/scheduler/ServerScheduler(326): pocketmine\scheduler\TaskHandler->run(integer 20401)
2017-09-26 [23:03:05] [Server thread/DEBUG]: #13 src/pocketmine/Server(2509): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 20401)
2017-09-26 [23:03:05] [Server thread/DEBUG]: #14 src/pocketmine/Server(2253): pocketmine\Server->tick()
2017-09-26 [23:03:05] [Server thread/DEBUG]: #15 src/pocketmine/Server(2132): pocketmine\Server->tickProcessor()
2017-09-26 [23:03:05] [Server thread/DEBUG]: #16 src/pocketmine/Server(1714): pocketmine\Server->start()
2017-09-26 [23:03:05] [Server thread/DEBUG]: #17 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/gsp_1476/g3.hmserv.eu-19132/PocketMine-MP.phar/, string /home/gsp_1476/g3.hmserv.eu-19132/, string /home/gsp_1476/g3.hmserv.eu-19132/plugins/)
2017-09-26 [23:03:05] [Server thread/DEBUG]: #18 /home/gsp_1476/g3.hmserv.eu-19132/PocketMine-MP.phar(1): require(string phar:///home/gsp_1476/g3.hmserv.eu-19132/PocketMine-MP.phar/src/pocketmine/PocketMine.php)`

**Comment by 95CivicSi** [comment] 2017-09-26 22:32
Issue closed as PiggyCustomEnchants doesn't currently support API 3.0.0-ALPHA8.

**Closed** 2017-09-26 22:31 UTC
Labels: Category: Bug, Status: Unconfirmed
