### ISSUE TITLE
getblock() on null

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [RevivalPMMP/PureEntitiesX#226] opened 2017-09-26 14:56 UTC
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
```
[14:49:35] [Server thread/INFO]: [asterW10: Killed asterW10]
[14:49:35] [Server thread/CRITICAL]: Could not tick level "world": Call to a member function getBlock() on null
[14:49:35] [Server thread/CRITICAL]: Error: "Call to a member function getBlock() on null" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 1466
[14:49:35] [Server thread/DEBUG]: #0 PureEntitiesX-MCPE-1.2/src/revivalpmmp/pureentities/entity/animal/WalkingAnimal(51): pocketmine\entity\Entity->isInsideOfWater()
[14:49:35] [Server thread/DEBUG]: #1 PureEntitiesX-MCPE-1.2/src/revivalpmmp/pureentities/entity/animal/WalkingAnimal(95): revivalpmmp\pureentities\entity\animal\WalkingAnimal->entityBaseTick(integer 1)
[14:49:35] [Server thread/DEBUG]: #2 src/pocketmine/level/Level(708): revivalpmmp\pureentities\entity\animal\WalkingAnimal->onUpdate(integer 14300)
[14:49:35] [Server thread/DEBUG]: #3 src/pocketmine/Server(2357): pocketmine\level\Level->doTick(integer 14300)
[14:49:35] [Server thread/DEBUG]: #4 src/pocketmine/Server(2512): pocketmine\Server->checkTickUpdates(integer 14300, double 1506437375.5528)
[14:49:35] [Server thread/DEBUG]: #5 src/pocketmine/Server(2253): pocketmine\Server->tick()
[14:49:35] [Server thread/DEBUG]: #6 src/pocketmine/Server(2132): pocketmine\Server->tickProcessor()
[14:49:35] [Server thread/DEBUG]: #7 src/pocketmine/Server(1714): pocketmine\Server->start()
[14:49:35] [Server thread/DEBUG]: #8 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///root/12/PocketMine-MP.phar/, string /root/12/, string /root/12/plugins/)
[14:49:35] [Server thread/DEBUG]: #9 /root/12/PocketMine-MP.phar(1): require(string phar:///root/12/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
```

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: (insert commit hash here)
Plugin Version: (insert commit hash here)
PHP version: 7.0.14 (default)

## Optional information
...

**Comment by TDMidkwhatisxd** [comment] 2017-09-26 14:57
what if you close/kill the mob is getblock is null?

**Comment by bluetigeresw** [comment] 2017-09-26 17:05
^ i had this issue a few days ago as well

**Comment by 95CivicSi** [comment] 2017-10-07 10:01
Duplicate of #221.  Updates to master as of 10/7/2017 should resolve this.

**Closed by 95CivicSi** 2017-10-07 10:01 UTC
Labels: Category: Bug, Status: Confirmed, Status: Work in Progress

**Comment by 95CivicSi** [comment] 2017-10-31 09:44
Linked an update in issue #239 that should fix this if you are still having problems.
