### ISSUE TITLE
Add Riding Feature to Horses, Llamas and Pigs

### ISSUE THREAD

**Issue by LagHD** [RevivalPMMP/PureEntitiesX#259] opened 2018-01-01 15:18 UTC
We need Riding, it's been a long-wanted feature that we've still been patiently waiting for ._.

**Comment by 95CivicSi** [comment] 2018-01-01 20:44
This feature is listed in the Bedrock TODO list.  

https://github.com/RevivalPMMP/PureEntitiesX/issues/236

**Comment by 95CivicSi** [comment] 2018-01-01 20:46
Duplicate of https://github.com/RevivalPMMP/PureEntitiesX/issues/246

**Comment by 95CivicSi** [comment] 2018-01-01 20:49
This will likely be added following the movement refactor and update to the AutoSpawnTask, however, I'm not going to guarantee an ETA.

**Comment by LagHD** [comment] 2018-01-01 23:31
Kk thanks

**Closed** 2018-02-15 23:35 UTC
Labels: Category: Duplicate, Category: Feature Request
