### ISSUE TITLE
Crashing when joining the game

### ISSUE THREAD

**Issue by singleparadox** [RevivalPMMP/PureEntitiesX#345] opened 2019-06-24 12:59 UTC
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

## Required Information
  __PocketMine-MP Version: 1.11.2__ (insert commit hash or version number here)
  __Plugin Version:0.6__ (insert commit hash or version number here)
  Where you got the plugin: https://poggit.pmmp.io/p/PureEntitiesX/0.6.0

## Optional Information
  __PHP version:__ 
  __Other Installed Plugins:__ 
  __OS Version:__
    
    

## Steps to reproduce the issue.
1.  Install the plugin
2.  Enter the server
3. Wait a few Seconds
3. Kicks you and throws an error
...

Unknown crash when using PureEntitiesX
  

```

24.06 09:02:51 [Server] Server thread/CRITICAL Error: "Undefined property: pocketmine\network\mcpe\protocol\MobArmorEquipmentPacket::$slots" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 164
24.06 09:02:51 [Server] Server thread/DEBUG #0 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/components/MobEquipment(625): pocketmine\network\mcpe\protocol\DataPacket->__set(string[5] slots, array[4])
24.06 09:02:51 [Server] Server thread/DEBUG #1 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/components/MobEquipment(278): revivalpmmp\pureentities\components\MobEquipment->createArmorEquipPacket()
24.06 09:02:51 [Server] Server thread/DEBUG #2 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/walking/Skeleton(66): revivalpmmp\pureentities\components\MobEquipment->sendEquipmentUpdate(object pocketmine\Player)
24.06 09:02:51 [Server] Server thread/DEBUG #3 src/pocketmine/entity/Entity(2045): revivalpmmp\pureentities\entity\monster\walking\Skeleton->sendSpawnPacket(object pocketmine\Player)
24.06 09:02:51 [Server] Server thread/DEBUG #4 src/pocketmine/entity/Entity(2055): pocketmine\entity\Entity->spawnTo(object pocketmine\Player)
24.06 09:02:51 [Server] Server thread/DEBUG #5 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/PureEntities(298): pocketmine\entity\Entity->spawnToAll()
24.06 09:02:51 [Server] Server thread/DEBUG #6 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(231): revivalpmmp\pureentities\PureEntities->scheduleCreatureSpawn(object pocketmine\level\Position, integer 34, object pocketmine\level\Level, string[7] hostile, boolean )
24.06 09:02:51 [Server] Server thread/DEBUG #7 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(292): revivalpmmp\pureentities\task\AutoSpawnTask->spawnPackToLevel(object pocketmine\math\Vector3, integer 34, object pocketmine\level\Level, string[7] hostile)
24.06 09:02:51 [Server] Server thread/DEBUG #8 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(118): revivalpmmp\pureentities\task\AutoSpawnTask->spawnHostileMob(object pocketmine\level\format\Chunk, object pocketmine\level\Level)
24.06 09:02:51 [Server] Server thread/DEBUG #9 src/pocketmine/scheduler/TaskHandler(159): revivalpmmp\pureentities\task\AutoSpawnTask->onRun(integer 7201)
24.06 09:02:51 [Server] Server thread/DEBUG #10 src/pocketmine/scheduler/TaskScheduler(199): pocketmine\scheduler\TaskHandler->run(integer 7201)
24.06 09:02:51 [Server] Server thread/DEBUG #11 src/pocketmine/plugin/PluginManager(689): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 7201)
24.06 09:02:51 [Server] Server thread/DEBUG #12 src/pocketmine/Server(2559): pocketmine\plugin\PluginManager->tickSchedulers(integer 7201)
24.06 09:02:51 [Server] Server thread/DEBUG #13 src/pocketmine/Server(2335): pocketmine\Server->tick()
24.06 09:02:51 [Server] Server thread/DEBUG #14 src/pocketmine/Server(2195): pocketmine\Server->tickProcessor()
24.06 09:02:51 [Server] Server thread/DEBUG #15 src/pocketmine/Server(1774): pocketmine\Server->start()
24.06 09:02:51 [Server] Server thread/DEBUG #16 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[40] /, string[48] /plugins/)
24.06 09:02:51 [Server] Server thread/DEBUG #17 (1): require(string[95] phar:///PocketMine-MP.phar/src/pocketmine)
24.06 09:02:51 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
24.06 09:02:51 [Server] Server thread/EMERGENCY Please upload the "/crashdumps/Mon_Jun_24-13.02.51-UTC_2019.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

```

**Comment by 95CivicSi** [comment] 2019-06-24 13:15
Duplicate of #344 and is already fixed on the main branch.

You can download a copy of the fixed version here:
https://poggit.pmmp.io/r/60547/PureEntitiesX_dev-294.phar

**Closed by 95CivicSi** 2019-06-24 13:15 UTC

**Comment by singleparadox** [comment] 2019-06-24 13:19
Thank you!
