### ISSUE TITLE
Players can no longer fly

### ISSUE THREAD

**Issue by fergatron** [RevivalPMMP/PureEntitiesX#257] opened 2017-12-23 19:58 UTC
## Required
__PocketMine-MP Version:__ PocketMine-MP 1.7dev-525 「[REDACTED]」 implementing API version 3.0.0-ALPHA10 for Minecraft: PE v1.2.7 (protocol version 160)
__Plugin Version:__ PureEntitiesX v0.2.8-3.dev3
__Plugin URL:__ https://poggit.pmmp.io/r/18519/PureEntitiesX.phar

### Optional
__PHP version:__ 7.20 (bin/php7)
__Other installed plugins:__ Worlds v1.0.13, SignPortal v1.1.3-3
__OS version:__ Fedora 25 (4.13.16-100.fc25.x86_64)

## Description
After installing the PEX plugin my other players cannot fly in creative mode. Oddly enough my player can-- he has "operator status."

**Comment by 95CivicSi** [comment] 2017-12-24 13:35
I have not been able to recreate this issue with PureEntitiesX.  Try removing the Worlds plugin and see if that solves your flying issues.

**Comment by 95CivicSi** [comment] 2017-12-26 13:40
Closing for now as I am certain this problem is due to the Worlds plugin.  Will reopen if evidence can be shown that this is caused by PureEntitiesX.

**Closed by 95CivicSi** 2017-12-26 13:40 UTC
Labels: Status: Unconfirmed
