### ISSUE TITLE
Server crashes when walking away from a tamed dog

### ISSUE THREAD

**Issue by 747project** [RevivalPMMP/PureEntitiesX#433] opened 2020-08-20 22:50 UTC
Link to crashdump: 
[Thu_Aug_20-22.26.59-UTC_2020.log](https://github.com/RevivalPMMP/PureEntitiesX/files/5105826/Thu_Aug_20-22.26.59-UTC_2020.log)

### Additional Details
The server crashes when I:
1. tame a wolf with a bone
2. tell the dog to stand
3. start to walk away

Crash dump attached in link above.

After the crash, when I restart the server and I rejoin the world, the dog disappears, and a second stacktrace appears in the logs:

```
2020-08-20 [22:33:10] [Server thread/CRITICAL]: TypeError: "Argument 2 passed to pocketmine\nbt\tag\CompoundTag::getLong() must be of the type int or null, float given, called in phar:///opt/minecraft/PocketMeServer/plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/traits/Tameable.php on line 117" (EXCEPTION) in "vendor/pocketmine/nbt/src/tag/CompoundTag" at line 243
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #0 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/traits/Tameable(117): pocketmine\nbt\tag\CompoundTag->getLong(string[8] OwnerEID, double -9.2233720368548E+18, boolean 1)
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #1 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/walking/Wolf(188): revivalpmmp\pureentities\entity\monster\walking\Wolf->loadTameNBT()
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #2 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/BaseEntity(204): revivalpmmp\pureentities\entity\monster\walking\Wolf->loadNBT()
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #3 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/walking/Wolf(71): revivalpmmp\pureentities\entity\BaseEntity->initEntity()
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #4 src/pocketmine/entity/Entity(637): revivalpmmp\pureentities\entity\monster\walking\Wolf->initEntity()
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #5 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/BaseEntity(105): pocketmine\entity\Entity->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #6 src/pocketmine/entity/Entity(380): revivalpmmp\pureentities\entity\BaseEntity->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #7 src/pocketmine/level/format/Chunk(700): pocketmine\entity\Entity::createEntity(string[4] Wolf, object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #8 src/pocketmine/level/Level(2681): pocketmine\level\format\Chunk->initChunk(object pocketmine\level\Level)
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #9 src/pocketmine/level/Level(2293): pocketmine\level\Level->loadChunk(integer 15, integer 23, boolean 1)
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #10 src/pocketmine/level/Level(2955): pocketmine\level\Level->getChunk(integer 15, integer 23, boolean 1)
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #11 src/pocketmine/Player(1053): pocketmine\level\Level->populateChunk(integer 15, integer 23)
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #12 src/pocketmine/Player(1852): pocketmine\Player->sendNextChunk()
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #13 src/pocketmine/Server(2401): pocketmine\Player->checkNetwork()
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #14 src/pocketmine/Server(2154): pocketmine\Server->tick()
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #15 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #16 src/pocketmine/Server(1588): pocketmine\Server->start()
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #17 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[30] /opt/minecraft/PocketMeServer/, string[38] /opt/minecraft/PocketMeServer/plugins/)
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #18 src/pocketmine/PocketMine(304): pocketmine\server()
2020-08-20 [22:33:10] [Server thread/CRITICAL]: #19 (11): require(string[85] phar:///opt/minecraft/PocketMeServer/PocketMine-MP.phar/src/pocketmine/PocketMin)
```

**Comment by 95CivicSi** [comment] 2020-08-21 04:45
Duplicate of #420 fixed in https://github.com/RevivalPMMP/PureEntitiesX/commit/2ee6720058b11ceef73c21672a9de7f66a44bfdb

Fix will be published with PureEntitiesX v 0.6.10

**Closed as completed by 95CivicSi** 2020-08-21 04:45 UTC
Labels: Category: Bug, Resolution: Fixed, Resolution: Duplicate
