### ISSUE TITLE
Pls read and fix mob animation

### ISSUE THREAD

**Issue by Scottishman** [RevivalPMMP/PureEntitiesX#370] opened 2020-02-07 15:11 UTC
I would love to have new animations for mobs because none of these are properly working. Mobs get stuck in blocks when you hit them. some mobs dont even have proper animation like rabbit.

**Comment by cyphr3x** [comment] 2020-05-19 21:53
Ill pay $100 for these problems to be fixed.
o dont get stuck
o dont sit there and just bounce up and down
reach out to me.  im serious about the payment.

**Comment by 95CivicSi** [comment] 2020-05-28 09:50
Duplicate of #369

**Closed by 95CivicSi** 2020-05-28 09:50 UTC
