### ISSUE TITLE
crash server !

### ISSUE THREAD

**Issue by roxtigger2003** [RevivalPMMP/PureEntitiesX#346] opened 2019-06-25 17:39 UTC
[17:37:07] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\MobArmorEquipmentPacket::$slots" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 164
[17:37:07] [Server thread/DEBUG]: #0 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/components/MobEquipment(625): pocketmine\network\mcpe\protocol\DataPacket->__set(string[5] slots, array[4])
[17:37:07] [Server thread/DEBUG]: #1 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/components/MobEquipment(278): revivalpmmp\pureentities\components\MobEquipment->createArmorEquipPacket()
[17:37:07] [Server thread/DEBUG]: #2 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/walking/Skeleton(66): revivalpmmp\pureentities\components\MobEquipment->sendEquipmentUpdate(object JackMD\NameSpaceRemover\CustomPlayer)
[17:37:07] [Server thread/DEBUG]: #3 src/pocketmine/entity/Entity(2045): revivalpmmp\pureentities\entity\monster\walking\Skeleton->sendSpawnPacket(object JackMD\NameSpaceRemover\CustomPlayer)
[17:37:07] [Server thread/DEBUG]: #4 src/pocketmine/entity/Entity(2055): pocketmine\entity\Entity->spawnTo(object JackMD\NameSpaceRemover\CustomPlayer)
[17:37:07] [Server thread/DEBUG]: #5 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/PureEntities(298): pocketmine\entity\Entity->spawnToAll()
[17:37:07] [Server thread/DEBUG]: #6 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(231): revivalpmmp\pureentities\PureEntities->scheduleCreatureSpawn(object pocketmine\level\Position, integer 34, object pocketmine\level\Level, string[7] hostile, boolean )
[17:37:07] [Server thread/DEBUG]: #7 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(292): revivalpmmp\pureentities\task\AutoSpawnTask->spawnPackToLevel(object pocketmine\math\Vector3, integer 34, object pocketmine\level\Level, string[7] hostile)
[17:37:07] [Server thread/DEBUG]: #8 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(118): revivalpmmp\pureentities\task\AutoSpawnTask->spawnHostileMob(object pocketmine\level\format\Chunk, object pocketmine\level\Level)
[17:37:07] [Server thread/DEBUG]: #9 src/pocketmine/scheduler/TaskHandler(159): revivalpmmp\pureentities\task\AutoSpawnTask->onRun(integer 5101)
[17:37:07] [Server thread/DEBUG]: #10 src/pocketmine/scheduler/TaskScheduler(199): pocketmine\scheduler\TaskHandler->run(integer 5101)
[17:37:07] [Server thread/DEBUG]: #11 src/pocketmine/plugin/PluginManager(689): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 5101)
[17:37:07] [Server thread/DEBUG]: #12 src/pocketmine/Server(2559): pocketmine\plugin\PluginManager->tickSchedulers(integer 5101)
[17:37:07] [Server thread/DEBUG]: #13 src/pocketmine/Server(2335): pocketmine\Server->tick()
[17:37:07] [Server thread/DEBUG]: #14 src/pocketmine/Server(2195): pocketmine\Server->tickProcessor()
[17:37:07] [Server thread/DEBUG]: #15 src/pocketmine/Server(1774): pocketmine\Server->start()
[17:37:07] [Server thread/DEBUG]: #16 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[40] C:\Users\Administrator\Desktop\Skyblock\, string[48] C:\Users\Administrator\Desktop\Skyblock\plugins\)
[17:37:07] [Server thread/DEBUG]: #17 (1): require(string[95] phar://C:/Users/Administrator/Desktop/Skyblock/PocketMine-MP.phar/src/pocketmine)
[17:37:07] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[17:37:07] [Server thread/EMERGENCY]: Please upload the "C:\Users\Administrator\Desktop\Skyblock\crashdumps/Tue_Jun_25-17.37.07-UTC_2019.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by 95CivicSi** [comment] 2019-06-25 17:53
Duplicate of #344 and #345

This problem has already been fixed.  Thr update has not been approved on Poggit yet but can be downloaded here:

https://poggit.pmmp.io/r/60547/PureEntitiesX_dev-294.phar

**Closed by 95CivicSi** 2019-06-25 17:53 UTC
