### ISSUE TITLE
Lag/Performance/Stability Issues

### ISSUE THREAD

**Issue by Magicode1** [RevivalPMMP/PureEntitiesX#163] opened 2017-03-23 12:19 UTC
Fix Lag and Performance Issues for PureEntitiesX. We will close this issue once it is done. 

Please note that this issue is taking precedence over other feature requests, but once we get the plugin running as smooth as possible, we will continue to add more features. (Rinse, Repeat. Right?)

**Comment by kniffo80** [comment] 2017-03-23 14:00
So I tried it out with changing the code to let entities only drop items when damaged by player. Sadly it's not the cause - it seems so. Will commit some stuff soon that we can work together in one and the same branch.

**Comment by kniffo80** [comment] 2017-03-23 16:07
I updated the kniffo80-dev branch - the peremove command is updated and is removing now all entities in all levels without player entities. So when the server lags badly maybe it's good idea to submit a peremove and check if it's running better then.

**Comment by kniffo80** [comment] 2017-03-24 08:16
So after testing out some stuff I'm really at the end of my (confined) knowledge. I deactivated the file logging and tested out some other stuff. But still this interesting observation from my side (or what I did):
1. Server was started with the plugin active
2. Login as a normal Player, doing some stuff - from time to time I send a peremove to remove all the entities
3. Logged out
4. Logged in again after 2 hours or so and the lagging starts
5. Stopped Server, deactivated plugin
6. Login again - the lag is still there
7. Logged in again this morning - looking around is a pain in the ass - it's VERY laggy

So - the plugin is not active anymore. There are zero entities living in the world. Shutdown of the server is no problem. But restart has no effect regarding the lags. I logged in a few seconds ago - lag is gone. So I'm really at the end of my ideas :worried: I'm afraid that is has nothing to do with the plugin.

**Comment by Sandertv** [comment] 2017-03-24 08:23
@kniffo80 is it FPS lag? (Screen moves slowly, low frames per second) or actual server side lag? (Delayed chat, particles etc.)

**Comment by kniffo80** [comment] 2017-03-24 08:26
@Sandertv that's an interesting question. Didn't try the chat but the chat seemed to be normal. It seems to be FPS lag. The screen has low FPS while moving ... what i will try when the lag comes again: clear the data on the client side and try again ... and maybe i will make a short video to demonstrate what I mean.

**Comment by Sandertv** [comment] 2017-03-24 08:28
Alright. If it is in fact FPS lag, and there are no entities even alive after you do /peremove command, then it is likely that something else is causing it.

**Comment by kniffo80** [comment] 2017-03-24 08:30
Yay. The most interesting thing: lag is still there even after deactivating the plugin. And as long as this problem isn't solved it makes no sense to continue implementing new features or solving issues. But that's only my opinion.

**Comment by Magicode1** [comment] 2017-03-24 13:48
I agree. Maybe next we need to do a LagRemover plugin XD

**Comment by jasonwynn10** [comment] 2017-03-24 14:06
It could be a client-side memory leak from a  packet that's causing the fps lag

**Comment by kniffo80** [comment] 2017-03-24 14:37
@jasonwynn10 the same assumption that i have n mind - but which :sweat:

**Comment by kniffo80** [comment] 2017-03-25 10:41
Now it gets interesting. I think it's mainly a client lag. Yesterday in the evening i had really bad lag. So i decided to wait until this morning without touching anything. And voila - today in the morning the lag was gone. Straaaaaange.

**Comment by kabluinc** [comment] 2017-03-26 20:16
Weird but for me its complete opposite. For the 3 days that I had this plugin it was TPS lag not FPS. The HUD (sends a constant popup to players) could be seen disappearing for upto 10 seconds some times and coming back. When doing /status the TPS would show between 6-12 TPS which is very low. Chat starts to delay heavily. Client side however there was no lag at all. Only server -side.

Since removing this plugin (over 2-3 weeks) iv never seen this issue happen a single time. Server runs for 7 hours before I restart it but no lag or delay what so ever.

**Comment by kniffo80** [comment] 2017-03-27 13:51
Updated plugin sources:

https://github.com/RevivalPMMP/PureEntitiesX/issues/156

**Comment by kniffo80** [comment] 2017-03-28 08:07
My server is now running for roundabout 20 hours with NBT **deactivated**. Everything is running fine and smooth without any lag - I logged in yesterday every hour to see, if anything lags. But no lag since yesterday. So my assumption: we're having NBT problems. There's an issue opened at PMMP: https://github.com/pmmp/PocketMine-MP/issues/466 which I think affects the performance when using living entities on a server.

But we need more testers here :weary: to confirm my assumption.

**Comment by Magicode1** [comment] 2017-03-28 11:21
I will try to test ASAP, although at the time I am away from my server computer most of the time. 

I would think that you are right about the NBT tags. How would you recommend we fix them?

**Comment by Sandertv** [comment] 2017-03-28 11:26
We wait 😄 It seems like this is a PMMP issue. It's reported on the PMMP repo by dktapps.

**Comment by kniffo80** [comment] 2017-03-28 11:53
How to fix ... either PMMP team fixes the stuff (I read there should be a complete rewrite of the NBT stuff) or we implement our own solution. Writing data to the disk on saveNBT and when an entity gets initialized, we read the data from disk. But that's not easy to implement. Then we would need a cleanup of the data (e.g. when an entity is older than x and not touched since x). This isn't easy to accomplish. But the client doesn't need NBT - it's only used for storing/restoring data when chunks are unloaded or the server restarts e.g.

**Comment by Magicode1** [comment] 2017-03-28 12:35
Hmm. Ok, it may just be better to wait then? What should we tackle in the meantime? :)

We have some more plugin/feature requests on our forums. Maybe we check those out?

**Comment by kniffo80** [comment] 2017-03-28 14:58
I will continue to work on the PureEntities plugin. There's a lot of work to be done. I think a good point would be this one: https://github.com/RevivalPMMP/PureEntitiesX/issues/161

New thing I would like to introduce is baby zombies. And adjust the speed values when they're babies (for all ageable entities currently implemented). And I would like to re-check the speed of all entities. They're moving too fast sometimes. So I'll try to adjust the speed values.

**Comment by kniffo80** [comment] 2017-03-29 08:53
Since yesterday my server is running with NBT active, after i've updated the server to latest PMMP. There were changes regarding the player - and now - since yesterday afternoon - everything runs fine and smooth also with NBT enabled. But I'm still unsure if it's gone now :unamused:

**Comment by Magicode1** [comment] 2017-03-29 11:28
Gotcha. I agree about #161 . Baby Zombies also :)

**Comment by kniffo80** [comment] 2017-03-29 17:53
Hmmmm... I was wrong about the fix. My server is lagging again :(

**Comment by kniffo80** [comment] 2017-03-30 08:10
As expected: today in the morning the server ran fine again. So it seems there's some sort of cleanup algorithm that cleans up NBT data or something similar. This is what I did (to exclude a memory leak):
1. set NBT tags to false in config and restart server -> not better
2. restart server without plugin enabled -> not better
3. leave NBT disabled and restarted server with plugin enabled -> not better
4. today in the morning, WITHOUT touching anything server sided -> lag free

I'm 99% sure it's about the NBT tags. BECAUSE:
1. there's no memory leak - otherwise the server would run fine after restart
2. it's not really a problem of the plugin - otherwise the server would run fine again when plugin gets disabled
3. running the server with the plugin enabled and NBT disabled has no lag after nearly 2 days running without a restart

I've the fear I cannot solve this issue without asking someone (especially dktapps) about a known cleanup algorithm where I can take a look at.

Btw: locally i can spawn baby zombies now - and they're fast :smile:

**Comment by kniffo80** [comment] 2017-04-03 08:49
Still no answer - or only silly ones - even in the forums. So I'll keep on investigating on this. I hope I can play around a little with /gc, /status and so on. The problem - it takes time :pensive:

**Comment by Magicode1** [comment] 2017-04-04 12:20
Yeah. Where did you ask on the forums? I didn't see it.

**Comment by kniffo80** [comment] 2017-04-04 12:33
https://forums.pmmp.io/threads/any-cleanup.1649/

But now finally - I got an answer. But it's not the answer to my original question :pensive: but i got some useful answers that I can check now.

**Comment by Magicode1** [comment] 2017-04-05 12:45
Sweet. School is whisking away all of my time, and I haven't been able to work on Plugins as much anymore, so I am sorry. I should be able to work more during summer break (We have a vacation for spring break) when the work load isn't so massive.

**Comment by kniffo80** [comment] 2017-04-06 10:47
I'm really tired of this. My server is now running for more than 3 days without any lag. I had some players on the server (including my son) and they played around with TNT i think. They digged a huge hole into the ground - and now - tadaaa the server is running without any issues with the plugin activated since 3 days! No lag at all. Everything is fine and smooth. AND everything is activated - from NBT storage to all the tasks - including the looking tasks. Straaaaange. Waiting until it's lagging again now :anguished:

**Comment by kniffo80** [comment] 2017-04-06 16:37
Still running fine. I remember I've changed my pocketmine.yml configuration. It's this here: https://pastebin.com/cjR0N4ie

Maybe try to experiment with the pocketmine settings file if anyone encounters lags / stability issues.

**Comment by kniffo80** [comment] 2017-04-14 14:48
And again - never had a lag again since then. Can anyone confirm? It's with the latest api3/network branch of PMMP.

**Comment by kniffo80** [comment] 2017-04-19 12:33
With latest api3/network branch I cannot see any performance lags anymore. Additionally I moved my PMMP server to a new VM and "improved" UDP performance on the server with the help of the following:

https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Web_Platform/5/html/Administration_And_Configuration_Guide/jgroups-perf-udpbuffer.html

Because: " ... One of the most common causes of lost UDP datagrams is an undersized receive buffer on the socket ..."

Maybe you can try it too - but it's only possible if you've a root server or a vserver with an own kernel (KVM virtualization e.g.).

For now I'll close this - first because nobody is confirming anything and for me - at least - i've no lag since days.

**Closed by kniffo80** 2017-04-19 12:33 UTC
Labels: Priority: High, Status: Approved, Status: Help Wanted, Status: Work in Progress

**Comment by jasonwynn10** [comment] 2017-04-19 12:35
I haven't had any lag either after recent branch updates
