### ISSUE TITLE
I'm using build 615. After that, your plugin starts spam by such a mistake:  

### ISSUE THREAD

**Issue by Daniil129932** [RevivalPMMP/PureEntitiesX#268] opened 2018-01-13 18:24 UTC
2018-01-12 [17:38:26]  [Server thread/DEBUG]: #8 /home/gs33423/PocketMine-MP.phar(1): require(string phar:///home/gs33423/PocketMine-MP.phar/src/pocketmine/PocketMine.php) 
2018-01-12 [17:38:26]  [Server thread/CRITICAL]: Could not execute task revivalpmmp\pureentities\task\EndermanLookingTask: Class 'pocketmine\utils\BlockIterator' not found 
20

2018-01-12 [17:43:56]  [Server thread/DEBUG]: #1 src/pocketmine/scheduler/TaskHandler(160): revivalpmmp\pureentities\task\InteractionTask->onRun(integer 9721) 
2018-01-12 [17:43:56]  [Server thread/DEBUG]: #2 src/pocketmine/scheduler/ServerScheduler(326): pocketmine\scheduler\TaskHandler->run(integer 9721) 
2018-01-12 [17:43:56]  [Server thread/DEBUG]: #3 src/pocketmine/Server(2536): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 9721) 
2018-01-12 [17:43:56]  [Server thread/DEBUG]: #4 src/pocketmine/Server(2279): pocketmine\Server->tick() 
2018-01-12 [17:43:56]  [Server thread/DEBUG]: #5 src/pocketmine/Server(2154): pocketmine\Server->tickProcessor() 
2018-01-12 [17:43:56]  [Server thread/DEBUG]: #6 src/pocketmine/Server(1742): pocketmine\Server->start() 
2018-01-12 [17:43:56]  [Server thread/DEBUG]: #7 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gs33423/, string /home/gs33423/plugins/) 
2018-01-12 [17:43:56]  [Server thread/DEBUG]: #8 /home/gs33423/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

When will you fix it?

**Comment by 95CivicSi** [comment] 2018-01-14 00:39
Duplicate of #266.  PureEntitiesX is not designed to work with the version of PocketMine-MP that you are using. This problem will not be resolved until the next release of PocketMine-MP and PureEntitiesX.  The appropriate release version of PocketMine-MP can be found here;

https://github.com/pmmp/PocketMine-MP/releases/tag/1.7dev-516

**Closed** 2018-01-14 00:40 UTC
Labels: Category: Duplicate, Status: Incomplete Issue Template
